const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '..', 'config.env') });

module.exports = {
  digicash: {
    serviceId: process.env.DIGICASH_SERVICE_ID,
    passwork: process.env.DIGICASH_PASSWORK,
    secretKey: process.env.DIGICASH_SECRET_KEY,
    baseUrl: process.env.DIGICASH_BASE_URL || 'https://api.fastpayph.com',
    endpoints: {
      pay: '/pay',
      payout: '/payout',
      status: '/status'
    }
  },
  server: {
    port: process.env.PORT || 3000,
    env: process.env.NODE_ENV || 'development'
  },
  callback: {
    url: process.env.CALLBACK_URL,
    returnUrl: process.env.RETURN_URL
  },
  test: {
    amount: process.env.TEST_AMOUNT_MINOR_UNITS || '10000',
    currency: process.env.TEST_CURRENCY || 'PHP'
  },
  paymentMethods: {
    pay: ['gcash', 'palawanpay', 'qrph', 'qrph-vip'],
    payout: ['instapay']
  },
  bankMappings: {
    'APHI': 'Alipay / Lazada Wallet',
    'OPDV': 'AllBank (A Thrift Bank), Inc.',
    'AUBK': 'Asia United Bank Corporation',
    'BFSR': 'Banana Fintech / BananaPay',
    'MRTC': 'Bangko Mabuhay (A Rural Bank), Inc.',
    'BKCH': 'Bank of China',
    'PABI': 'Bank of Commerce, Inc.',
    'BPDI': 'BanKo, A Subsidiary of BPI',
    'ONNR': 'BDO Network Bank, Inc.',
    'BNOR': 'BDO Unibank, Inc.',
    'BIUU': 'Binangonan Rural Bank / BRBDigital',
    'BOPI': 'BPI / VYBE by BPI',
    'RUCA': 'Camalig Bank',
    'CNRL': 'Cantilan Bank Inc',
    'CBMF': 'Card Bank, Inc.',
    'CAMZ': 'CARD MRI RBI',
    'CRMH': 'CARD SME BANK',
    'CELR': 'Cebuana Lhuillier Bank / Cebuana Xpress',
    'CHSV': 'China Bank Savings, Inc.',
    'CHBK': 'China Banking Corporation',
    'CIPH': 'CIMB Bank Philippines Inc.',
    'CIYC': 'CIS Bayad Center / Bayad',
    'CIVA': 'City Savings Bank',
    'CTCB': 'CTBC Bank (Philippines) Corporation',
    'DCPH': 'DCPay / COINS.PH',
    'DBPH': 'Development Bank of the Philippines',
    'DCDE': 'Dumaguete City Development Bank',
    'DUMT': 'Dungganon Bank (A Microfinance Rural Bank), Inc.',
    'EWBC': 'East West Banking Corporation',
    'EAWR': 'East West Rural Bank / Komo',
    'EAGM': 'Easy Pay Global EMI Corp',
    'ENRU': 'Entrepreneur Bank Inc. (A Rural Bank)',
    'EQSN': 'Equicom Savings Bank, Inc.',
    'GXCH': 'G-Xchange / GCash',
    'GOTY': 'GoTyme Bank',
    'GHPE': 'GrabPay',
    'HSBC': 'HSBC',
    'IREM': 'I-Remit/iCASH',
    'IFIP': 'Infoserve / Nationlink',
    'INGB': 'ING Bank N.V.',
    'ISTH': 'ISLA Bank (A Thrift Bank), Inc.',
    'TLBP': 'LANDBANK / OFBank',
    'LESI': 'Legazpi Savings Bank, Inc.',
    'LUDV': 'Luzon Development Bank',
    'MAAR': 'Malayan Bank Savings and Mortgage Bank, Inc.',
    'MAYC': 'MARCOPAY',
    'PAPH': 'Maya / Paymaya Philippines, Inc.',
    'MYDB': 'Maya Bank, Inc.',
    'MBBE': 'Maybank Philippines, Inc.',
    'MBTC': 'Metropolitan Bank and Trust Company',
    'MIOC': 'Mindanao Consolidated CoopBank',
    'CUOB': 'Netbank',
    'OMNP': 'Omnipay, Inc.',
    'OWNB': 'Own Bank The Rural Bank of Cavite City Inc.',
    'PASV': 'Pacific Ace Savings Bank',
    'PPSF': 'PalawanPay',
    'PRTO': 'Partner Rural Bank (Cotabato), Inc.',
    'PAEY': 'PayMongo',
    'CPHI': 'Philippine Bank of Communications',
    'PPBU': 'Philippine Business Bank, Inc., A Savings Bank',
    'PDAX': 'Philippine Digital Asset Exchange, Inc., / PDAX',
    'PNBM': 'Philippine National Bank',
    'PHSB': 'Philippine Savings Bank',
    'PHVB': 'Philippine Veterans Bank',
    'PHTB': 'PhilTrust Bank',
    'PSCO': 'Producers Bank',
    'QCDF': 'Queen City Development Bank',
    'QCRI': 'Quezon Capital Rural Bank, Inc.',
    'RARL': 'Rang-Ay Bank',
    'RCBC': 'RCBC/DiskarTech',
    'ROBP': 'Robinsons Bank',
    'RUGU': 'Rural Bank of Guinobatan / Asenso',
    'LAUI': 'Seabank PH',
    'SETC': 'Security Bank Corporation',
    'SHPH': 'ShopeePay',
    'SPEY': 'SpeedyPay/eMango Pay',
    'SCBL': 'Standard Chartered Bank',
    'STLA': 'Sterling Bank of Asia, Inc., A Savings Bank',
    'SUSV': 'Sun Savings Bank, Inc.',
    'TAYO': 'TayoCash',
    'TOKT': 'TOKTOKWALLET',
    'TDBI': 'Tonik Bank',
    'TRXP': 'TraxionPay/DigiCOOP/COOPNET',
    'UCSV': 'UCPB Savings Bank, Inc.',
    'UBPH': 'Union Bank of the Philippines',
    'UNOD': 'UnionDigital Bank',
    'UCPB': 'United Coconut Planters Bank',
    'UNOB': 'UNOBank',
    'USME': 'USSC Money Services',
    'WEDV': 'Wealth Development Bank Corporation',
    'TRWI': 'Wise Pilipinas Inc.',
    'ZBTE': 'Zybi Tech Inc. / JuanCash'
  },
  transactionStatuses: {
    pay: ['awaiting_redirect', 'processing', 'paid', 'fail', 'expired', 'initiated'],
    callback: ['PROCESSING', 'PAID', 'FAIL', 'EXPIRED']
  }
};